### ISSUE TITLE
Issue with Latch / FF tab

### ISSUE THREAD

**Issue by justincdas** [fsmMLK/inkscapeLogicGates#6]
i am getting following error when i try to place Latch or FF.

Traceback (most recent call last):
  File "logicGates.py", line 682, in <module>
    logic.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "logicGates.py", line 122, in effect
    asynPreset=int(so.latchPreset),asynClear=int(so.latchClear),size=so.latchSize,suppressq=so.latchSuppressq, suppressNOTq=so.latchSuppressNOTq)
  File "logicGates.py", line 637, in createLatch
    self.createOutput(True,group,position=[x_max,position[1]+dist_signal],extraLength=0.0,label='notQ',name=u'\u00ACQ',fontSizeFactor=fontSizeFactorG)
  File "logicGates.py", line 266, in createOutput
    self.createSignal(flagTrue,parent,[position[0],position[1]],direction,extraLength,label,name,fontSizeFactor)
  File "logicGates.py", line 234, in createSignal
    inkDraw.text.latex(self,group,name,position=posText,fontSize=self.fontSize*fontSizeFactor,refPoint=justif,preambleFile=self.preambleFile)
  File "inkscapeMadeEasy_Draw.py", line 1256, in latex
    groupLatex = text.write(ExtensionBaseObj, LaTeXtext, [0, 0], parent,textStyle=mytextStyle, fontSize=fontSize/0.76,justification=justification, angleDeg=0.0) # attention! keep angleDeg=0.0 here bc it will be rotated below
  File "inkscapeMadeEasy_Draw.py", line 1108, in write
    myTspan.text = textLines[n].decode('utf-8')   
  File "C:\Program Files\Inkscape\lib\python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xac' in position 0: ordinal not in range(128)

**Comment by fsmMLK** [comment]
what encode are you using in your machine?

**Comment by dmjacobson** [comment]
I don’t know.  This problem occurred when I was employed at Qualcomm, using a laptop issued by the IT department.  I was running Ubuntu Linux as a virtual machine on top of Windows 10.  When I retired (for the second time) last May, I had to turn in the laptop.  

Sorry,
    —David
